language: go
cache: true

go:
  - 1.4
  - 1.3

before_install:
  - export GOPATH=$SHIPPABLE_GOPATH

install:
  - if ! go get code.google.com/p/go.tools/cmd/cover; then go get golang.org/x/tools/cmd/cover; fi
  - go get github.com/mattn/goveralls
  - ./hack/travis/install-etcd.sh
  - ./hack/verify-gofmt.sh
  - ./hack/verify-boilerplate.sh
  - ./hack/verify-description.sh
  - ./hack/travis/install-std-race.sh
  - ./hack/build-go.sh

before_script:
  - mkdir -p shippable/codecoverage

script:
  - PATH=$HOME/gopath/bin:./third_party/etcd:$PATH ./hack/test-cmd.sh
  - PATH=$HOME/gopath/bin:./third_party/etcd:$PATH ./hack/verify-gendocs.sh
  - PATH=$HOME/gopath/bin:./third_party/etcd:$PATH ./hack/test-integration.sh
  - go test -coverprofile=coverage.txt -covermode count ./
  - $GOPATH/bin/gocover-cobertura < coverage.txt > shippable/codecoverage

notifications:
  irc: "chat.freenode.net#google-containers"
